### ISSUE TITLE
There are lots of compile errors after import by cocoapods

### ISSUE THREAD

**Issue by nutts** [jcavar/refresher#14]
My Podfile is as the following:

platform :ios, '8.0'

use_frameworks!

pod "AFNetworking", "~> 2.0"
pod "SwiftyJSON", ">= 2.2"
pod 'Alamofire', '~> 1.2'
pod 'SwiftDate'
pod 'Refresher'

-------------------------
After successfully installed the Refresher, there are lots of Compile Error happened. see attached screenshot.
![screen shot 2015-06-11 at 5 01 41 pm](https://cloud.githubusercontent.com/assets/3438727/8103536/d27a2c8e-105b-11e5-8b87-762d0136a6a2.png)

**Comment by jcavar** [comment]
Hey, I am sorry for this. 
I have published new podfile, you can just run 'pod update' and it should be fixed.
