### ISSUE TITLE
use tabbarcontroller view 

### ISSUE THREAD

**Issue by ibmsoft** [jcavar/refresher#15]
when uitableviewcontroller in tabbarviewcontroller
use this in tableview,can not display correct
![image](https://cloud.githubusercontent.com/assets/26042/8198105/71c7fefc-14d4-11e5-8219-6cbd7d79574b.png)

**Comment by jcavar** [comment]
I am not completely sure what is happening, but this looks like navigation bar is translucent. Can you try to change that and try again?
