### ISSUE TITLE
Refresher doesn't build for iOS 9 targets

### ISSUE THREAD

**Issue by matthewjsummers** [jcavar/refresher#26]
Hi there

Are there any plans for refresher to support iOS 9? After upgrading to Xcode 7.0.1 (which defaults to build against iOS 9), Refresher no longer builds (e.g. in 'AnimatorView' label.setTranslatesAutoresizingMaskIntoConstraints(false) is deprecated in favour of label.translatesAutoresizingMaskIntoConstraints = false).

**Comment by jcavar** [comment]
Hey there, 
I definitely plan to support iOS9 but I am currently busy so haven't had time to do it yet. Hopefully, I will review pull requests regarding over weekend and I think we will have it then.

**Comment by matthewjsummers** [comment]
Awesome. Just seen that kennydust has these fixes so will borrow those until they are merged!

**Comment by jcavar** [comment]
Great!

**Comment by jcavar** [comment]
This should be resolved now. There is new 0.5.0 pod release for Swift 2.
