### ISSUE TITLE
Activate refresh by programming ?

### ISSUE THREAD

**Issue by ins0u** [jcavar/refresher#30]
Hello,

I have a small question, how to activate the refresh programmatically?

After returning from a function, I would like to update the list and trigger a refresh by code ..
Is it possible ?

Thank you for your help :)

**Comment by jcavar** [comment]
Hi, yes there is a way to do that :)
https://github.com/jcavar/refresher/blob/master/Refresher/PullToRefreshExtension.swift#L64

**Comment by ins0u** [comment]
Thank you 👍 ^^
