### ISSUE TITLE
 module compiled with Swift 2.3 cannot be imported in Swift 3.0

### ISSUE THREAD

**Issue by Gopitech21** [jcavar/refresher#33]
error: module compiled with Swift 2.3 cannot be imported in Swift 3.0: /Users/***********/Build/Products/Debug-iphoneos/Refresher/Refresher.framework/Modules/Refresher.swiftmodule/arm64.swiftmodule

**Comment by jcavar** [comment]
Yes, this requires some work to support Swift 3. I am not sure when I will have time to check this though.

**Comment by nevinjethmalani** [comment]
Would it be possible for you to give us an estimated time on when you might be able to add support for swift 3.0. Really love what you have done and we need to migrate to swift 3.0 but are waiting for this pod.

**Comment by jcavar** [comment]
Now when Swift 3 is out, I will try to look into it as soon as I can.

**Comment by jcavar** [comment]
Refresher 0.6.1 is now out with Swift 3 support. You can give it a try!
