### ISSUE TITLE
Framework not showing in finder

### ISSUE THREAD

**Issue by nomitechy** [jcavar/refresher#4]
i am not able to import the framework in my project .. i tried method 2 .. show in finder doesnt show anything :( plz help btw i rele love it <3

**Comment by jcavar** [comment]
Did you try to build for device(not simulator)?

**Comment by nomitechy** [comment]
![ios simulator screen shot jan 12 2015 9 56 06 am](https://cloud.githubusercontent.com/assets/10147631/5712746/16b40336-9ac6-11e4-9a42-8e50df277af4.png)
see this is my app and i want add ur pull to refresh .. help plz :)

**Comment by jcavar** [comment]
@nomitechy can you screenshot your Products group in Xcode?

**Comment by nomitechy** [comment]
its a uiview not tableview .. can u provide me wid some codes also 
![screenshot 2015-01-13 01 52 09](https://cloud.githubusercontent.com/assets/10147631/5712847/f430a58e-9ac6-11e4-8c32-0f780386a9e9.png)
![screenshot 2015-01-13 01 52 48](https://cloud.githubusercontent.com/assets/10147631/5712851/f893ded4-9ac6-11e4-925b-ea8ab45e7013.png)

**Comment by jcavar** [comment]
![screen shot 2015-01-12 at 23 54 54](https://cloud.githubusercontent.com/assets/3751289/5712892/7707c160-9ab6-11e4-8b99-038b5da7cdc3.png)
I need this

**Comment by nomitechy** [comment]
![screenshot 2015-01-13 01 56 31](https://cloud.githubusercontent.com/assets/10147631/5712910/74ebf296-9ac7-11e4-846e-b0f27e63df0d.png)

**Comment by jcavar** [comment]
Ok, but not your app but Refresher

**Comment by nomitechy** [comment]
oh ok hold on ..

**Comment by nomitechy** [comment]
![screenshot 2015-01-13 02 02 03](https://cloud.githubusercontent.com/assets/10147631/5713015/3f56567a-9ac8-11e4-83bb-165c79f79c4f.png)

**Comment by jcavar** [comment]
It is in red, can you change from iPhone6 simulator to your device and then build?

**Comment by nomitechy** [comment]
actually i dont have developer id right now ..

**Comment by nomitechy** [comment]
i think it wont run on my iphone

**Comment by nomitechy** [comment]
should i send u my project ?

**Comment by jcavar** [comment]
Unfortunately it is required to build for device for frameworks to work. Please try second method or you can use this one
https://www.dropbox.com/s/0juo9z4m69m38km/Refresher.framework.zip?dl=0

**Comment by nomitechy** [comment]
Thnx

**Comment by jcavar** [comment]
You are welcome :)

**Comment by nomitechy** [comment]
now i have imported framework .. what all should i import ?

**Comment by jcavar** [comment]
"import Refresher" only

**Comment by nomitechy** [comment]
u mean the folder ?

**Comment by jcavar** [comment]
I don't understand question. What specific problem do you have?

**Comment by nomitechy** [comment]
![screenshot 2015-01-13 02 40 49](https://cloud.githubusercontent.com/assets/10147631/5713466/ba5bb0a4-9acd-11e4-9424-2d272be2817e.png)

**Comment by jcavar** [comment]
You can't add pull to refresh to UIView, please take a look at example app.

**Comment by nomitechy** [comment]
oh .. so how should i refresh my view ?

**Comment by nomitechy** [comment]
with a button ??

**Comment by nomitechy** [comment]
u dere ?

**Comment by jcavar** [comment]
I don't know what are your specific requirements, but yes, button can be possible solution.
