### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by jarimartens10** [jcavar/refresher#5]
Hi, is there a possibility that you add iOS 7 support to the framework?

If not, which functions would be missing on iOS 7?

It is giving me this warning in xcode:

    embedded dylibs/frameworks only run on iOS 8 or later

Can this warning be ignored?
Will the app be rejected?

**Comment by jcavar** [comment]
Hi,
I don't have plans about iOS 7 support, but I think it should work. Problem with iOS 7 is that it doesn't support frameworks, so you can try to simply add files in your project.
