### ISSUE TITLE
Cocoapods error

### ISSUE THREAD

**Issue by Lukaz32** [jcavar/refresher#6]
I've installed the framework through Cocoapods. When I build it Xcode presents the following error:

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

What might be going on?

**Comment by jcavar** [comment]
Which version of Cocoapods and Xcode do you use?

**Comment by Lukaz32** [comment]
Cocoapods 0.35.0 and Xcode 6.1.1

**Comment by jcavar** [comment]
As mentioned here http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/
Cocoapods 0.36 supports frameworks, so please first upgrade and try again.

**Comment by Lukaz32** [comment]
Alright. I'll give it try. Thanks.
